---
factors:
  - name: "powerlaw"
    type: "PowerLawFlux"
    pivot_energy: 1.0E+5
    baseline_norm: 1.0E-18
  - name: "conv_norm"
    type: "FluxNorm"
  - name: "prompt_norm"
    type: "FluxNorm"
  - name: delta_gamma
    type: "DeltaGamma"
    reference_energy: 2617.3148996675773
  - name: snowstorm_escale
    type: "SnowstormGauss"
    sys_gauss_width: 0.05
    sys_sim_bounds: [0.9, 1.1]
    req_variable_name: "e_scaling"
  - name: snowstorm_esmear
    type: "SnowstormGauss"
    sys_gauss_width: 0.05
    sys_sim_bounds: [0.9, 1.1]
    req_variable_name: "e_smearing"
  - name: barr_gradients
    type: "GradientReweight"
    gradient_key:
        barr_h: "barr_h_gradient"
        barr_w: "barr_w_gradient"
        barr_z: "barr_z_gradient"
        barr_y: "barr_y_gradient"
    baseline_weight: "conv_weight"
  - name: "CR_intp"
    type: "ModelInterpolator"
    base_key:
      conv: "conv_weight"
      prompt: "prompt_weight"
    alt_key: 
      conv: "conv_weight_alt"
      prompt: "prompt_weight_alt"
  - name: "effective_veto"
    type: "VetoThreshold"
    threshold_a: 
      conv: "log_PF_at100GeV_conv_a"
      prompt: "log_PF_at100GeV_pr_a"
    threshold_b: 
      conv: "log_PF_at100GeV_conv_b"
      prompt: "log_PF_at100GeV_pr_b"
    threshold_c: 
      conv: "log_PF_at100GeV_conv_c"
      prompt: "log_PF_at100GeV_pr_c"
    rescale_energy: 100
    anchor_energy: 100

hist_factors:
  - name: SnowStormSystematics
    type: SnowStormGradient
    parameters: ["dom_eff", "ice_abs", "ice_scat", "ice_holep0", "ice_holep1"]
    MC_variables: ["DOMEfficiency", "IceAbsorption", "IceScattering", "HoleIceForward_p0", "HoleIceForward_p1"]
    default: [1.0, 1.0, 1.0, -0.27, -0.042]
    split_values: [1.0, 1.0, 1.0, -0.27, -0.042]
    range: [[0.9, 1.1], [0.9, 1.1], [0.9, 1.1], [-0.84, 0.3], [-0.134, 0.05]]
    gradient_pickle: "/data/ana/Diffuse/GlobalFit/NNMFit/snowstorm_gradients/snowstorm_v2_All_FullSamples_DroppedBins_cscd_15zen.pickle"
    det_configs:
      Northern Tracks: "IC86_pass2_SnowStorm_v2_tracks"
      Cascades: "IC86_pass2_SnowStorm_v2_cscd_cascade"
      Cascades Muon: "IC86_pass2_SnowStorm_v2_cscd_muon"
  - name: MuonTemplate
    type: ScaledTemplate
    det_configs:
      Northern Tracks: "IC86_pass2_SnowStorm_v2_tracks"
    template_file: "/data/ana/Diffuse/GlobalFit/NNMFit/templates/Tracks_CorsikaMuon_Fullrange_drop_5lowEbins.pickle"
  - name: MuonGunTemplate
    type: ScaledTemplate
    det_configs:
      Cascades: "IC86_pass2_SnowStorm_v2_cscd_cascade"
      Cascades Muon: "IC86_pass2_SnowStorm_v2_cscd_muon"
    template_file: "/data/ana/Diffuse/GlobalFit/NNMFit/templates/cscd_muongun_ALL_KDE_15zen_manual_ssq.pickle"

components:
  - name: "astro"
    factors: ["powerlaw"]
  - name: "conv"
    factors: ["conv_norm", "delta_gamma", "barr_gradients", "CR_intp", "effective_veto"]
  - name: "prompt"
    factors: ["prompt_norm", "delta_gamma", "CR_intp", "effective_veto"]


model:
  name: "model"
  components:
  - name: "astro"
    baseline_weight: "baseline_weight"
  - name: "conv"
    baseline_weight: "conv_weight"
  - name: "prompt"
    baseline_weight: "prompt_weight"

datasets:
  - name: Northern Tracks
    lifetime: 257989333.37
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["reco_energy", "log", [2.5,7,46]]
        - ["reco_zenith", "cos", [-1, 0.0872, 34]]
    det_conf: "IC86_pass2_SnowStorm_v2_tracks"
    hist_factors: ["SnowStormSystematics", "MuonTemplate"] 
  - name: Cascades
    lifetime: 295598014.33
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["reco_energy", "log", [2.8,7,22]]
        - ["reco_zenith", "cos", [-1, 1, 16]]
    det_conf: "IC86_pass2_SnowStorm_v2_cscd_cascade"
    hist_factors: ["SnowStormSystematics", "MuonGunTemplate"] 
  - name: Cascades Muon
    lifetime: 295598014.33
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["reco_energy", "log", [2.6, 4.8, 2]]
        - ["reco_zenith", "cos", [-1, 1, 2]]
    det_conf: "IC86_pass2_SnowStorm_v2_cscd_muon"
    hist_factors: ["SnowStormSystematics", "MuonGunTemplate"] 
    excluded_comps: []



    
