---
factors:
  - name: "powerlaw"
    type: "PowerLawFlux"
    pivot_energy: 1.0E+5
    baseline_norm: 1.0E-18
    param_mapping:
      flux_norm: "astro_norm"
      spectral_index: "astro_index"
  - name: "conv_norm"
    type: "FluxNorm"
    param_mapping:
      flux_norm: "conv_norm"
  - name: "prompt_norm"
    type: "FluxNorm"
    param_mapping:
      flux_norm: "prompt_norm"
  - name: delta_gamma
    type: "DeltaGamma"
    reference_energy: 2617.3148996675773
  - name: snowstorm_escale
    type: "SnowstormGauss"
    sys_gauss_width: 0.05
    sys_sim_bounds: [0.9, 1.1]
    req_variable_name: "e_scaling"
  - name: snowstorm_esmear
    type: "SnowstormGauss"
    sys_gauss_width: 0.05
    sys_sim_bounds: [0.9, 1.1]
    req_variable_name: "e_smearing"
  - name: barr_gradients
    type: "GradientReweight"
    gradient_key_mapping:
        barr_h: "barr_h_gradient"
        barr_w: "barr_w_gradient"
        barr_z: "barr_z_gradient"
        barr_y: "barr_y_gradient"
    baseline_weight: "conv_weight"
  - name: "CR_intp_conv"
    type: "ModelInterpolator"
    baseline_weight: "conv_weight"
    alternative_weight: "conv_weight_alt"
  - name: "CR_intp_prompt"
    type: "ModelInterpolator"
    baseline_weight: "prompt_weight"
    alternative_weight: "prompt_weight_alt"
  - name: "effective_veto_conv"
    type: "VetoThreshold"
    threshold_a: "log_PF_at100GeV_conv_a"
    threshold_b: "log_PF_at100GeV_conv_b"
    threshold_c: "log_PF_at100GeV_conv_c"
    rescale_energy: 100
    anchor_energy: 100
  - name: "effective_veto_prompt"
    type: "VetoThreshold"
    threshold_a: "log_PF_at100GeV_pr_a"
    threshold_b: "log_PF_at100GeV_pr_b"
    threshold_c: "log_PF_at100GeV_pr_c"
    rescale_energy: 100
    anchor_energy: 100

components:
  - name: "astro"
    factors: ["powerlaw"]
  - name: "conv_veto"
    factors: ["conv_norm", "delta_gamma", "barr_gradients", "CR_intp_conv", "effective_veto_conv"]
  - name: "prompt_veto"
    factors: ["prompt_norm", "delta_gamma", "CR_intp_prompt", "effective_veto_prompt"]
  - name: "conv"
    factors: ["conv_norm", "delta_gamma", "barr_gradients", "CR_intp_conv"]
  - name: "prompt"
    factors: ["prompt_norm", "delta_gamma", "CR_intp_prompt"]


models:
  - name: "model_veto"
    components:
    - name: "astro"
      baseline_weight: "baseline_weight"
    - name: "conv_veto"
      baseline_weight: "conv_weight"
    - name: "prompt_veto"
      baseline_weight: "prompt_weight"
  - name: "model_noveto"
    components:
    - name: "astro"
      baseline_weight: "baseline_weight"
    - name: "conv"
      baseline_weight: "conv_weight"
    - name: "prompt"
      baseline_weight: "prompt_weight"


datasets:
  - name: Northern Tracks
    model: model_noveto
    lifetime: 257989333.37
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["log10_reco_energy", [2.5,7,46]]
        - ["cos_reco_zenith", [-1, 0.0872, 34]]
    hist_factors:
      - name: SnowStormSystematicsNT
        type: SnowStormGradient
        parameters: ["dom_eff", "ice_abs", "ice_scat", "ice_holep0", "ice_holep1"]
        gradient_names: ["DOMEfficiency", "IceAbsorption", "IceScattering", "HoleIceForward_p0", "HoleIceForward_p1"]
        default: [1.0, 1.0, 1.0, -0.27, -0.042]
        split_values: [1.0, 1.0, 1.0, -0.27, -0.042]
        range: [[0.9, 1.1], [0.9, 1.1], [0.9, 1.1], [-0.84, 0.3], [-0.134, 0.05]]
        gradient_pickle: "/home/chaack/data/snowstorm_IC86_pass2_SnowStorm_v2_tracks.pickle"
      - name: MuonTemplate
        type: ScaledTemplate
        template_file: "/home/chaack/data/Tracks_CorsikaMuon_Fullrange_drop_5lowEbins.pickle"
        param_mapping:
          template_norm: "muon_template"
  - name: Cascades
    model: model_veto
    lifetime: 295598014.33
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["log10_reco_energy",  [2.8,7,22]]
        - ["cos_reco_zenith",  [-1, 1, 16]]
    hist_factors: 
      - name: SnowStormSystematicsCasc
        type: SnowStormGradient
        parameters: ["dom_eff", "ice_abs", "ice_scat", "ice_holep0", "ice_holep1"]
        gradient_names: ["DOMEfficiency", "IceAbsorption", "IceScattering", "HoleIceForward_p0", "HoleIceForward_p1"]
        default: [1.0, 1.0, 1.0, -0.27, -0.042]
        split_values: [1.0, 1.0, 1.0, -0.27, -0.042]
        range: [[0.9, 1.1], [0.9, 1.1], [0.9, 1.1], [-0.84, 0.3], [-0.134, 0.05]]
        gradient_pickle: "/home/chaack/data/snowstorm_IC86_pass2_SnowStorm_v2_cscd_cascade.pickle"
      - name: MuonGunTemplateCascade
        type: ScaledTemplate
        template_file: "/home/chaack/data/cscd_muongun_cscd_cascade_KDE_15zen_manual_ssq.pickle"
        param_mapping:
          template_norm: "muongun_template"
      
  - name: Cascades Muon
    model: model_veto
    lifetime: 295598014.33
    binning:
      type: RectangularBinning
      bin_vars_edges:
        - ["log10_reco_energy",  [2.6, 4.8, 2]]
        - ["cos_reco_zenith",  [-1, 1, 2]]
    hist_factors:
      - name: SnowStormSystematicsCascMu
        type: SnowStormGradient
        parameters: ["dom_eff", "ice_abs", "ice_scat", "ice_holep0", "ice_holep1"]
        gradient_names: ["DOMEfficiency", "IceAbsorption", "IceScattering", "HoleIceForward_p0", "HoleIceForward_p1"]
        default: [1.0, 1.0, 1.0, -0.27, -0.042]
        split_values: [1.0, 1.0, 1.0, -0.27, -0.042]
        range: [[0.9, 1.1], [0.9, 1.1], [0.9, 1.1], [-0.84, 0.3], [-0.134, 0.05]]
        gradient_pickle: "/home/chaack/data/snowstorm_IC86_pass2_SnowStorm_v2_cscd_muon.pickle"
      - name: MuonGunTemplateMuon
        type: ScaledTemplate
        template_file: "/home/chaack/data/cscd_muongun_cscd_muon_KDE_15zen_manual_ssq.pickle"
        param_mapping:
          template_norm: "muongun_template"
